# Generated by Django 3.0.6 on 2020-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('userpwd', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Tuser',
            },
        ),
    ]
