# Generated by Django 3.0.6 on 2020-07-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tcourse',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tcourse',
            },
        ),
        migrations.CreateModel(
            name='Tterm',
            fields=[
                ('termid', models.AutoField(primary_key=True, serialize=False)),
                ('termname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tterm',
            },
        ),
        migrations.CreateModel(
            name='TSelectCourse',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(db_column='courseid', on_delete=django.db.models.deletion.CASCADE, to='sc.Tcourse')),
                ('term', models.ForeignKey(db_column='termid', on_delete=django.db.models.deletion.CASCADE, to='sc.Tterm')),
            ],
            options={
                'db_table': 'TSelectCourse',
            },
        ),
    ]
