# Generated by Django 3.0.6 on 2020-07-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcalldate',
            fields=[
                ('calldateid', models.AutoField(primary_key=True, serialize=False)),
                ('calldate', models.DateTimeField()),
                ('selectcourse', models.ForeignKey(db_column='scid', on_delete=django.db.models.deletion.CASCADE, to='sc.TSelectCourse')),
            ],
            options={
                'db_table': 'Tcalldate',
            },
        ),
        migrations.CreateModel(
            name='Tstudent',
            fields=[
                ('stuid', models.AutoField(primary_key=True, serialize=False)),
                ('stuno', models.CharField(max_length=50)),
                ('stuname', models.CharField(max_length=50)),
                ('selectcourse', models.ForeignKey(db_column='scid', on_delete=django.db.models.deletion.CASCADE, to='sc.TSelectCourse')),
            ],
            options={
                'db_table': 'Tstudent',
            },
        ),
        migrations.CreateModel(
            name='Tcallrec',
            fields=[
                ('callrecid', models.AutoField(primary_key=True, serialize=False)),
                ('iscall', models.BooleanField()),
                ('calltime', models.DateTimeField(null=True)),
                ('callip', models.CharField(max_length=45, null=True)),
                ('calldate', models.ForeignKey(db_column='calldateid', on_delete=django.db.models.deletion.CASCADE, to='roll.Tcalldate')),
                ('student', models.ForeignKey(db_column='stuid', on_delete=django.db.models.deletion.CASCADE, to='roll.Tstudent')),
            ],
            options={
                'db_table': 'Tcallrec',
            },
        ),
    ]
